### ISSUE TITLE
Farming location bug

### ISSUE THREAD

**Issue by Ace-Stargale** [SquidDev/farming-hell#10]
There's no farming location listed for the Caster, Assassin and Berserker Pieces. Not sure if it's an issue with the Atlas Academy spreadsheet or what, but figured I should report it.
<img width="651" alt="Screenshot 2024-12-01 at 12 38 26 PM" src="https://github.com/user-attachments/assets/3b510b5f-8c2d-447a-ba7c-94a9dabe9d7d">

**Comment by SquidDev** [comment]
Thanks for the report! Yeah, weirdly the drop rate is missing from these three entries, so the script I wrote to import this data skipped over those rows. This should be now fixed.

![](https://github.com/user-attachments/assets/d7ab9de8-468d-4ca5-b217-1c4d99a3caaa)
