### ISSUE TITLE
Summer/Space Ereshkigal

### ISSUE THREAD

**Issue by VictoriaPkmn** [SquidDev/farming-hell#9]
Hi, I plan on summon Summer/Space Ereshkigal in two years. Can you add her to the planner please? So I can see her materials requirements and plan accordingly. I would appreciate it. Thank you.
VictoriaPkmn :D

**Comment by SquidDev** [comment]
Thanks for the report! Confusingly she's just called "Ereshkigal" in the game file, so won't show up if you search for "Space" or "Summer".

I've made a couple of changes so she should show up whichever you search now :).

**Comment by VictoriaPkmn** [comment]
> Thanks for the report! Confusingly she's just called "Ereshkigal" in the game file, so won't show up if you search for "Space" or "Summer".
> 
> I've made a couple of changes so she should show up whichever you search now :).

Thank you!
VictoriaPkmn :D
